models:
  - name: stg__fhv_bases
    description: ""
    columns:
      - name: base_number
        description: ""

      - name: base_name
        description: ""

      - name: dba
        description: ""

      - name: dba_category
        description: ""

      - name: filename
        description: ""

  - name: stg__bike_data
    description: ""
    columns:
      - name: started_at_ts
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: ended_at_ts
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist

      - name: tripduration
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist

      - name: start_station_id
        description: ""

      - name: start_station_name
        description: ""

      - name: start_lat
        description: ""

      - name: start_lng
        description: ""

      - name: end_station_id
        description: ""

      - name: end_station_name
        description: ""

      - name: end_lat
        description: ""

      - name: end_lng
        description: ""

      - name: filename
        description: ""


  - name: stg__central_park_weather
    description: ""
    columns:
      - name: station
        description: ""

      - name: name
        description: ""

      - name: date
        description: ""

      - name: awnd
        description: ""

      - name: prcp
        description: ""

      - name: snow
        description: ""

      - name: snwd
        description: ""

      - name: tmax
        description: ""

      - name: tmin
        description: ""

      - name: filename
        description: ""

  - name: stg__fhv_tripdata
    description: ""
    columns:
      - name: dispatching_base_num
        description: ""
        tests:
          - not_null

      - name: pickup_datetime
        description: ""

      - name: dropoff_datetime
        description: ""

      - name: pulocationid
        description: ""

      - name: dolocationid
        description: ""

      - name: affiliated_base_number
        description: ""

      - name: filename
        description: ""

  - name: stg__fhvhv_tripdata
    description: ""
    columns:
      - name: hvfhs_license_num
        description: ""

      - name: dispatching_base_num
        description: ""

      - name: originating_base_num
        description: ""

      - name: request_datetime
        description: ""

      - name: on_scene_datetime
        description: ""

      - name: pickup_datetime
        description: ""

      - name: dropoff_datetime
        description: ""

      - name: pulocationid
        description: ""

      - name: dolocationid
        description: ""

      - name: trip_miles
        description: ""

      - name: trip_time
        description: ""

      - name: base_passenger_fare
        description: ""

      - name: tolls
        description: ""

      - name: bcf
        description: ""

      - name: sales_tax
        description: ""

      - name: congestion_surcharge
        description: ""

      - name: airport_fee
        description: ""

      - name: tips
        description: ""

      - name: driver_pay
        description: ""

      - name: shared_request_flag
        description: ""

      - name: shared_match_flag
        description: ""

      - name: access_a_ride_flag
        description: ""
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bool
          - not_null

      - name: wav_request_flag
        description: ""

      - name: wav_match_flag
        description: ""

      - name: filename
        description: ""
